#!/usr/bin/env bash
# Register the nanobrowser native-messaging host with Chrome and Chromium.
#
#   ./install.sh [<extension-id>] [--dev]
#
# With no <extension-id>, the ID is derived from the `key` in ../wxt.config.ts.
# NB_HOME=<dir> writes the whole tree somewhere else (used by tests; keeps the
# real profile untouched).
set -euo pipefail

HOST_NAME=com.nanobrowser.host
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
NB_HOME=${NB_HOME:-$HOME}
DEV=0
EXT_ID=""

for arg in "$@"; do
  case "$arg" in
    --dev) DEV=1 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    -*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *) EXT_ID="$arg" ;;
  esac
done

# --- extension id -----------------------------------------------------------
if [ -z "$EXT_ID" ]; then
  if [ -f "$REPO/wxt.config.ts" ]; then
    KEY=$(grep -oE "'MII[A-Za-z0-9+/=]+'" "$REPO/wxt.config.ts" | head -n1 | tr -d "'") || true
    if [ -n "${KEY:-}" ]; then
      EXT_ID=$(printf '%s' "$KEY" | base64 -d | sha256sum | head -c 32 | tr '0-9a-f' 'a-p')
      echo "derived extension id from wxt.config.ts key: $EXT_ID"
    fi
  fi
fi
if [ -z "$EXT_ID" ]; then
  echo "error: no extension id given and none derivable from $REPO/wxt.config.ts" >&2
  exit 1
fi
if ! printf '%s' "$EXT_ID" | grep -qE '^[a-p]{32}$'; then
  echo "error: '$EXT_ID' is not a 32-character Chrome extension id" >&2
  exit 1
fi

# --- node --------------------------------------------------------------------
# Chrome launches the host from the desktop session, not a login shell, so it never
# sees mise's PATH injection. Resolve node now and bake the absolute path in.
NODE_BIN=$(mise which node 2>/dev/null || true)
[ -n "$NODE_BIN" ] || NODE_BIN=$(command -v node || true)
if [ -z "$NODE_BIN" ] || [ ! -x "$NODE_BIN" ]; then
  echo "error: could not resolve an executable node (tried 'mise which node', then PATH)" >&2
  exit 1
fi
echo "node: $NODE_BIN ($("$NODE_BIN" --version))"

# --- wrapper -----------------------------------------------------------------
# #!/usr/bin/env node would break: the kernel passes everything after the
# interpreter as ONE argument to env. Use /bin/sh + exec instead.
WRAPPER="$HERE/bin/nanobrowser-host"
mkdir -p "$HERE/bin"
{
  echo '#!/bin/sh'
  echo '# GENERATED BY host/install.sh -- absolute paths are baked in on purpose.'
  [ "$DEV" = "1" ] && echo 'NANOBROWSER_DEV=1; export NANOBROWSER_DEV'
  echo "exec \"$NODE_BIN\" \"$HERE/src/main.ts\" \"\$@\""
} > "$WRAPPER"
chmod 0755 "$WRAPPER"
echo "wrapper: $WRAPPER (dev=$DEV)"

# --- manifests ---------------------------------------------------------------
MANIFEST=$(cat <<JSON
{
  "name": "$HOST_NAME",
  "description": "nanobrowser local host: secrets, LLM proxy, run log, dev trigger.",
  "path": "$WRAPPER",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXT_ID/"
  ]
}
JSON
)

for dir in "$NB_HOME/.config/google-chrome/NativeMessagingHosts" \
           "$NB_HOME/.config/chromium/NativeMessagingHosts"; do
  mkdir -p "$dir"
  printf '%s\n' "$MANIFEST" > "$dir/$HOST_NAME.json"
  chmod 0644 "$dir/$HOST_NAME.json"
  echo "installed: $dir/$HOST_NAME.json"
done

mkdir -p "$NB_HOME/.local/share/nanobrowser/runs"
echo "done. Reload the extension in chrome://extensions after installing."
